laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('contato', 'HomeController@contatoPost')->name('contato.post');
    Route::post('agendamento', 'HomeController@agendamentoPost')->name('agendamento.post');
    Route::get('mensagens', 'MensagensController@index')->name('mensagens');
    Route::get('oracoes', 'OracoesController@index')->name('oracoes');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload'); 
        Route::post('order', 'PainelController@order'); 
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::get('calendario', 'CalendarioController@index')->name('calendario.index');
        Route::get('calendario/{dia}/{mes}/{ano}', 'CalendarioController@show')->name('calendario.show');
        Route::post('calendario/save', 'CalendarioController@store')->name('calendario.store');
        Route::post('calendario/delete', 'CalendarioController@destroy')->name('calendario.destroy');
        Route::get('agendamentos/confirmados', 'AgendamentosController@listarConfirmados')->name('agendamentos.confirmados');
        Route::resource('agendamentos', 'AgendamentosController');
        Route::resource('institucional', 'InstitucionalController', ['only' => ['index', 'update']]);
        Route::resource('oracoes', 'OracoesController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
        
        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Agendamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Agendamento extends Model
{
    protected $table = 'agendamentos';

    protected $guarded = ['id'];

    protected $fillable = [
        'nome', 'email', 'telefone', 'confirmado', 'calendario_id', 'tipo_atendimento_id',
    ];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function calendario()
    {
        return $this->belongsTo('App\Models\Calendario', 'calendario_id')->ordenados();
    }

    public function tipoAtendimento()
    {
        return $this->belongsTo('App\Models\TipoAtendimento', 'tipo_atendimento_id')->ordenados();
    }

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeNaoConfirmados($query)
    {
        return $query->where('confirmado', '!=', 1);
    }

    public function countNaoConfirmados()
    {
        return $this->naoConfirmados()->count();
    }
}

laravel/app/Http/Controllers/Painel/AgendamentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Http\Requests\AgendamentosRequest;
use App\Models\Agendamento;
use App\Models\Calendario;
use App\Models\TipoAtendimento;
use Illuminate\Support\Facades\Mail;

class AgendamentosController extends Controller
{
    public function index()
    {
        $agendamentos = Agendamento::orderBy('created_at', 'DESC')->get();

        return view('painel.agendamentos.index', compact('agendamentos'));
    }

    public function show($id)
    {
        $pedido = $id;

        $calendario = Calendario::find($pedido->calendario_id);

        $tipoAtendimento = TipoAtendimento::find($pedido->tipo_atendimento_id);

        return view('painel.agendamentos.show', compact('pedido', 'calendario', 'tipoAtendimento'));
    }

    public function update(Agendamento $agendamento, Request $request)
    {
        try {

            $agendamento->update([
                'confirmado' => !$agendamento->confirmado
            ]);

            $this->sendMail($agendamento);

            return redirect()->route('painel.agendamentos.index')->with('success', 'Pedido de agendamento confirmado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar pedido de agendamento: ' . $e->getMessage()]);
        }
    }

    public function destroy(Agendamento $agendamento)
    {
        try {

            $agendamento->delete();
            return redirect()->route('painel.agendamentos.index')->with('success', 'Pedido de agendamento excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir pedido: ' . $e->getMessage()]);
        }
    }

    public function listarConfirmados()
    {
        $agendamentosConfirmados = Agendamento::where('confirmado', 1)->orderBy('created_at', 'DESC')->get();

        return view('painel.agendamentos.confirmados', compact('agendamentosConfirmados'));
    }

    private function sendMail(Agendamento $agendamento)
    {
        $calendario = Calendario::find($agendamento->calendario_id);
        $tipoAtendimento = TipoAtendimento::find($agendamento->tipo_atendimento_id);

        $dadosEmail = array(
            'data' => $calendario->data,
            'horario' => $calendario->horario,
            'tipoAtendimento' => $tipoAtendimento->tipo,
            'nome' => $agendamento->nome,
        );

        if (isset($agendamento->email)) {
            Mail::send('emails.agendamento', $dadosEmail, function ($message) use ($agendamento) {
                $message->to($agendamento->email, $agendamento->nome)
                    ->subject('[AGENDAMENTO] Cris dos Anjos')
                    ->from('exemplo@email.com', '[AGENDAMENTO] Cris dos Anjos');
            });
        }
    }
}

laravel/app/Http/Controllers/Painel/CalendarioController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\Calendario;
use App\Helpers\Tools;
use Carbon\Carbon;

class CalendarioController extends Controller
{
    public function index()
    {
        if (empty($_GET["data"])) {
            $dados = $this->getCalendarioDia(date("d/m/Y"));
        } else {
            $dados = $this->getCalendarioDia($_GET["data"]);
        }

        return view('painel.calendario.index', compact('dados'));
    }

    public function show($dia, $mes, $ano)
    {
        $data = $dia . "/" . $mes . "/" . $ano;

        $dados = $this->getCalendarioDia($data);

        return response()->json($dados);
    }

    public function store(Request $request, Calendario $registro)
    {
        try {
            $data = $request['data'];
            $horario = $request['horario'];

            $dataFormat = \Carbon\Carbon::createFromFormat('d/m/Y', $data)->format('Y-m-d');

            $findId = Calendario::where('data', $dataFormat)->where('horario', $horario)->value('id');

            if (isset($findId)) {
                $dados = ['liberado' => 1];
                $registro->where('id', $findId)->update($dados);
            } else {
                $dados = [
                    'data' => $dataFormat,
                    'horario' => $horario,
                    'liberado' => 1
                ];
                $registro->create($dados);
            }

            return redirect()->route('calendario.index', compact('data'))->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Request $request, Calendario $registro)
    {
        try {
            $data = $request['data'];
            $horario = $request['horario'];

            $dataFormat = \Carbon\Carbon::createFromFormat('d/m/Y', $data)->format('Y-m-d');

            $findId = Calendario::where('data', $dataFormat)->where('horario', $horario)->value('id');

            $registro->where('id', $findId)->delete();

            return redirect()->route('calendario.index', compact('data'))->with('success', 'Registro removido com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao remover registro: ' . $e->getMessage()]);
        }
    }

    private function getCalendarioDia($data)
    {
        $dataFormat = \Carbon\Carbon::createFromFormat('d/m/Y', $data)->format('Y-m-d');
        $registros = Calendario::where('data', $dataFormat)->get();

        $inicio = new \DateTime('07:30');
        $intervalo = 14.5 * 2; // 08:00 as 22:00 -> total 29 horarios

        for ($i = 0; $i < $intervalo; $i++) {

            $horarios[] = $inicio->add(new \DateInterval('PT30M'))->format('H:i');
            $registroHorario = $registros->where('horario', $horarios[$i]);

            if ($registroHorario->isEmpty()) { // se vazio
                $dados[] =  [$horarios[$i], 0];
            } else {
                foreach ($registroHorario as $registro) {

                    if (empty($registro)) {
                        $dados[] =  [$horarios[$i], 0];
                    } else {
                        if ($registro->liberado == 1) {
                            $dados[] =  [$horarios[$i], 1];
                        } else {
                            $dados[] =  [$horarios[$i], 0];
                        }
                    }
                }
            }
        }

        return $dados;
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Models\Configuracoes;
use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Models\Contato;
use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: ' . $e->getMessage()]);
        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/GeneratorController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Artisan;

class GeneratorController extends Controller
{
    public function index()
    {
        return view('painel.generator.index');
    }

    public function submit(Request $request)
    {
        $this->validate($request, [
            'type'         => 'required',
            'resourceName' => 'required',
            'unitName'     => 'required_if:type,default'
        ]);

        $type = $request->get('type');

        $parameters = [
            'resourceName' => $request->get('resourceName'),
            'fields'       => $request->get('fields'),
        ];

        if(!empty($request->get('campos_nome')[0])) {
            $fields = '';
            foreach ($request->get('campos_nome') as $key => $campo_nome) {
                $field = [
                    $campo_nome,
                    $request->get('campos_tipo')[$key],
                    $request->get('campos_validation')[$key]
                ];

                $field = implode(':', $field);

                if (array_key_exists($key+1, $request->get('campos_nome'))) {
                    $fields .= $field.',';
                } else {
                    $fields .= $field;
                }
            }

            if (!empty($request->get('fields'))) {
                $parameters['fields'] = $request->get('fields').','.$fields;
            } else {
                $parameters['fields'] = $fields;
            }
        }

        if ($type == 'default') {
            $parameters['unitName'] = $request->get('unitName');
            $parameters['--slug']   = $request->get('slug');

            if ($request->get('paginate')) {
                $parameters['--paginate'] = $request->get('paginate');
            }
            if ($request->get('sortable')) {
                $parameters['--sortable'] = true;
            }
            if ($request->get('gallery')) {
                $parameters['--gallery'] = true;
            }
            if ($request->get('categories')) {
                $parameters['--categories'] = true;
            }
            if ($request->get('tags')) {
                $parameters['--tags'] = true;
            }
        }

        if ($request->get('force')) {
            $parameters['--force'] = true;
        }

        try {

            Artisan::call('resource:'.$type, $parameters);
            $output = Artisan::output();

            return back()->with(compact('output'))->withInput();

        } catch (\Exception $e) {

            return back()->withErrors([$e->getMessage()])->withInput();

        }

    }
}

laravel/resources/views/painel/agendamentos/confirmados.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>Agendamentos Confirmados</h2>
</legend>

@if(!count($agendamentosConfirmados))
<div class="alert alert-warning" role="alert">Nenhum agendamento confirmado.</div>
@else
<table class="table table-striped table-bordered table-hover data-table">
    <thead>
        <tr>
            <th>Data</th>
            <th>Horário</th>
            <th>Tipo</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
        </tr>
    </thead>

    <tbody>
        @foreach ($agendamentosConfirmados as $agendamento)
        <tr class="tr-row @if(!$agendamento->confirmado) warning @endif">
            <td>{{ date('d/m/Y', strtotime(App\Models\Calendario::find($agendamento['calendario_id'])->data)) }}</td>
            <td>{{ App\Models\Calendario::find($agendamento['calendario_id'])->horario }}</td>
            <td>{{ App\Models\TipoAtendimento::find($agendamento['tipo_atendimento_id'])->tipo }}</td>
            <td>{{ $agendamento->nome }}</td>
            <td>
                <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $agendamento->email }}" style="margin-right:5px;border:0;transition:background .3s">
                    <span class="glyphicon glyphicon-copy"></span>
                </button>
                {{ $agendamento->email }}
            </td>
            <td>{{ $agendamento->telefone }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@stop

laravel/resources/views/painel/agendamentos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>Pedidos de agendamento recebidos</h2>
</legend>

@if(!count($agendamentos))
<div class="alert alert-warning" role="alert">Nenhum pedido de agendamento recebido.</div>
@else
<table class="table table-striped table-bordered table-hover data-table">
    <thead>
        <tr>
            <th>Data Pedido</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($agendamentos as $agendamento)

        <tr class="tr-row @if(!$agendamento->confirmado) warning @endif">
            <td data-order="{{ $agendamento->created_at_order }}">{{ $agendamento->created_at }}</td>
            <td>{{ $agendamento->nome }}</td>
            <td>
                <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $agendamento->email }}" style="margin-right:5px;border:0;transition:background .3s">
                    <span class="glyphicon glyphicon-copy"></span>
                </button>
                {{ $agendamento->email }}
            </td>
            <td>{{ $agendamento->telefone }}</td>
            <td class="crud-actions">
                <div class="btn-group btn-group-sm">

                    <a href="{{ route('painel.agendamentos.show', $agendamento->id ) }}" class="btn btn-primary btn-sm pull-left" style="margin-right:5px;">
                        <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Detalhes
                    </a>

                    {!! Form::open([
                    'route' => ['painel.agendamentos.destroy', $agendamento->id],
                    'method' => 'delete'
                    ]) !!}
                    <button type="submit" class="btn btn-danger btn-sm btn-delete" style="margin-right:5px;"><span class="glyphicon glyphicon-remove" style="margin-right:10px;margin-left:10px;"></span></button>
                    {!! Form::close() !!}

                    {!! Form::open([
                    'route' => ['painel.agendamentos.update', $agendamento->id],
                    'method' => 'patch'
                    ]) !!}

                    @if(!$agendamento->confirmado)
                    <button type="submit" class="btn btn-sm pull-left btn-confirmar-agendamento btn-success"><span class="glyphicon small glyphicon-ok" style="margin-right:10px;margin-left:10px;"></span></button>
                    @endif
                    
                    {!! Form::close() !!}

                </div>
            </td>
        </tr>

        @endforeach
    </tbody>
</table>
@endif

@stop

laravel/resources/views/painel/agendamentos/show.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2>Pedido de agendamento</h2>
    </legend>

    <div class="form-group">
        <label>Data do pedido</label>
        <div class="well">{{ $pedido->created_at }}</div>
    </div>

    <div class="form-group">
        <label>Tipo de atendimento</label>
        <div class="well">{{ $tipoAtendimento->tipo }}</div>
    </div>

    <div class="form-group">
        <label>Data de atendimento</label>
        <div class="well">{{ $calendario->data }}</div>
    </div>

    <div class="form-group">
        <label>Horário de atendimento</label>
        <div class="well">{{ $calendario->horario }}</div>
    </div>

    <div class="form-group">
        <label>Nome</label>
        <div class="well">{{ $pedido->nome }}</div>
    </div>

    <div class="form-group">
        <label>E-mail</label>
        <div class="well">
            <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $pedido->email }}" style="margin-right:5px;border:0;transition:background .3s">
                <span class="glyphicon glyphicon-copy"></span>
            </button>
            {{ $pedido->email }}
        </div>
    </div>

@if($pedido->telefone)
    <div class="form-group">
        <label>Telefone</label>
        <div class="well">{{ $pedido->telefone }}</div>
    </div>
@endif

    

    <a href="{{ route('painel.agendamentos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop